Create search
drink-this/drink-this-frontend pull request #14
Opened 2021-07-28 15:12 UTC by zachjamesgreen

## Pull request checklist
Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Rubocop has passed locally and any fixes were made for failures
- [ ] Build is passing
    build is not passing because AppActions.js is deleted
## Pull request type
Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):
## What is the current behavior?

Issue Number: 
closes #
## What is the new behavior?

- 
- 
- 
## Does this introduce a breaking change?
- [ ] Yes
- [x] No

Created search component and search results component . tests for those components are passing. added query string package to parse the query from the path since react doesn't do it for us anymore. created header component with logo and search component and rendered in it.

2021-07-29 02:51 UTC, twarbelow commented
does it matter that ci isn't passing yet?

2021-07-29 03:33 UTC, zachjamesgreen commented
yeah a failing build is fin for now. there isn't a config file for circle to find so it fails it

2021-07-29 19:33 UTC, markcyen approved these changes
Looks great to me! Can't wait to see it!

2021-07-29 19:33 UTC, markcyen commented on src/components/SearchResults.js
> +    return parsed.q;
Sweet search box...

2021-07-29 19:33 UTC, markcyen commented on src/components/SearchResults.js
> +                <a className="text-base mt-4 hover:underline cursor-pointer">Cocktail {i}</a>
Looks like when a user hovers over this image, it'll show something? Nice feature if that is the case...

2021-07-29 19:33 UTC, markcyen commented on src/test/Search.test.js
> +  // setup a DOM element as a render target
Oh... I'll want to learn about testing in JS.

2021-07-30 19:49 UTC, twarbelow requested changes
- there are file naming descrepencies that should be addressed, but that isn't too big a deal
- the main thing I'm having an issue with is 'SearchResults' being undefined in the app.js. I've attached a screenshot
<img width="1283" alt="Screen Shot 2021-07-30 at 12 48 16 PM" src="https://user-images.githubusercontent.com/10294841/127704543-2cf1421b-70f9-4b07-a528-8bf5b8e485e8.png">

2021-07-30 21:28 UTC, twarbelow approved these changes

2021-07-30 21:29 UTC, merged